server:
  port: 8080
---
spring:
    profiles: default
musicbrainz:
    baseURI: http://musicbrainz.org
wikipedia:
    baseURI: https://en.wikipedia.org
coverArtArchive:
    baseURI: http://coverartarchive.org